name: yildizetal2022

dependencies:
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - poetry
  - python
  - pyyaml
  - rasterio
  - rpy2
  - scikit-learn
  - scipy
  - setuptools
  - r-base
  - r-robustgasp